### PR TITLE
Bump version to 1.0

### PR DESCRIPTION
**Pull request by yuvipanda**
Major version bump, since #31 is a breaking change.

### CODE REVIEW

**Comment by consideRatio** [comment]
Here is output from github-activity @yuvipanda. I've also created #33 which allow us to follow the instructions in RELEASE.md again.

```
#### Bugs fixed

* Log out old user when new user logs in [#31](https://github.com/jupyterhub/ltiauthenticator/pull/31) ([@U4I-fedir-kryvytskyi](https://github.com/U4I-fedir-kryvytskyi))

#### Contributors to this release

([GitHub contributors page for this release](https://github.com/jupyterhub/ltiauthenticator/graphs/contributors?from=2019-12-11&to=2020-11-12&type=c))

[@ptcane](https://github.com/search?q=repo%3Ajupyterhub%2Fltiauthenticator+involves%3Aptcane+updated%3A2019-12-11..2020-11-12&type=Issues) | [@U4I-fedir-kryvytskyi](https://github.com/search?q=repo%3Ajupyterhub%2Fltiauthenticator+involves%3AU4I-fedir-kryvytskyi+updated%3A2019-12-11..2020-11-12&type=Issues)
```

**Review by consideRatio — APPROVED** [review]
1.0.0 :tada: :heart:! :)

**Review by consideRatio — APPROVED** [review]
LGTM! Mergy merge?

**Comment by yuvipanda** [comment]
Awesome! Thanks, @consideRatio! I guess I've to tag and push now for PyPI publishing?

**Comment by consideRatio** [comment]
@yuvipanda yepp!

**Pull request merged**
