### PR TITLE
Lti 1.1 make oauth_callback optional

### PR DESCRIPTION
**Pull request by martinclaus**
The `oauth_callback` parameter in the launch request is not required by LTI 1.1 and some tool consumer do not provide them in the request. According to th e[LTI 1.1 implementation notes](https://www.imsglobal.org/specs/ltiv1p1/implementation-guide#toc-4), setting a default value value is fine.

See #136

### CODE REVIEW

**Comment by dennis531** [comment]
I receive the following error code: 
image

I think this happens because the signature base string is changed by the default parameter added in the code. Thus, different signatures will be calculated. In https://oauth.net/core/1.0/#rfc.section.9.1 the composition of the string is described.

**Comment by martinclaus** [comment]
@dennis531 Thank you for testing this PR! I have made the `oauth_callback` parameter optional, as you suggested initially. Can you please test again the latest commit?

**Comment by dennis531** [comment]
Now it works, thanks!

**Comment by martinclaus** [comment]
Great! Thank you again for testing this PR!

**Pull request merged**
