### PR TITLE
[WIP] LTI 1.3 Authenticator

### LINKED ISSUE #38: Add an LTI 1.3 Authenticator
Currentl, we support an LTI 1.1 based Authenticator. LTI 1.3 is a significant improvement, and we should support that too. An additional authenticator here is probably the way to go

### PR DESCRIPTION
**Pull request by jgwerner**
- Adds LTI 1.3 Authenticator with standard login initiation flow from the Platform (LMS) to the Tool (the JupyterHub)
- Adds tests

Closes #38

### CODE REVIEW

**Comment by jgwerner** [comment]
@yuvipanda I still have some work to do to clean up tests and hope to get to them soon. There are a lot of changes with this PR so if you think we should add the LTI 1.3 authenticator in more granular iterations then let me know.

**Comment by yuvipanda** [comment]
YAY for working on this, @jgwerner! Excited to see this work happen and get merged.

I think going through #2 first is a good idea. Do you think you will be able to do that as well? Doens't necessarily have to be that exact PR, but similar structural split would be nice.

I also think vscode had formatted all the files with black in this PR :D I think black formatting is a good idea, but can we do that as a separate PR? That way, this will be easier to review.

Once we go through this, I'd love for us to write a blog post for the Jupyter blog. Would you be interested? :D

**Comment by jgwerner** [comment]
Hi @yuvipanda sounds good! I'll incorporate the changes from #2 and send separate chore PR for formatting/linking. I was getting afraid that this one was getting way too huge!

**Comment by yuvipanda** [comment]
@jagwar awesome! Looking forward to it :)

**Comment by jgwerner** [comment]
@yuvipanda #41 and #40 have been updated - I'll get to work on this PR as soon as they are merged.

**Comment by yuvipanda** [comment]
I've now merged #44. Thank you very much for your patience, @jgwerner!

**Pull request closed without merging**
