### PR TITLE
(feat) (lti13): Allow multiple LTI 1.3 client ids

### PR DESCRIPTION
**Pull request by martinclaus**
Note that I chose `trailtlets.List` as container type (not `traitlets.Set`) to mitigate [yaml configuration limitations](https://z2jh.jupyter.org/en/latest/resources/reference.html#hub-config).

See #151

### CODE REVIEW

**Comment by martinclaus** [comment]
@jeflem: I have implemented your proposed changes with an additional tweak in the ID token validation (`azp` claim validation). Do you have capacity to test this branch in your setup? I am guessing that you are not using a helm chart for configuration but the standard `jupyterhub_config.py`, correct?

I will test on a kubernetes deployment configured via yaml files.

**Comment by jeflem** [comment]
Tested your code on a 'classical' JupyterHub install (with `jupyterhub_config.py`): works like a charm. LMS was Moodle 4. This feature makes integrating JupyterHub into an LMS much easier. Thank you so much @martinclaus!

**Comment by martinclaus** [comment]
Tested on [zero2jupyterhub v1.2.0](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/tree/1.2.0) with string value, single item list and list with multiple items. Everything works as expected.

Ready to merge IMO.

**Comment by consideRatio** [comment]
@martinclaus there are limitatiosn in YAML, but the traitlet's Set type accepts being passed a List.

For example [`Authenicator.admin_users` is a traitlets Set type](https://github.com/jupyterhub/jupyterhub/blob/efdad701df46bb8f4242961ae896a247a1b39b37/jupyterhub/auth.py#L102-L121), and we can still pass it Lists parsed from YAML like below:

```yaml
hub:
  config:
    JupyterHub:
      admin_access: true
      admin_users:
        - jovyan1
        - jovyan2
```

**Comment by martinclaus** [comment]
> there are limitatiosn in YAML, but the traitlet's Set type accepts being passed a List.

Thank you for the clarification. I then go for `traitlets.Set` as the container type since it feels more appropriate.

**Comment by martinclaus** [comment]
@consideRatio Is this ready to be merged?

**Review by consideRatio — APPROVED** [review]
Nice this looks great to me!

Thanks for pinging me, keep doing that for any review effort you need to help you drive development @martinclaus!

:heart: :tada: :sunflower: thank you for working on this project!!

**Pull request merged**
